### PR TITLE
New user agents

### PR DESCRIPTION
**Pull request by ToonSpinISAAC**
Hi, I've found some more bot user agent strings. This pull request adds 37 different ones. I've added them in a commit, and then made a new commit that sorts the newly created list by alphabet, to organize things a little bit.

These user agents combine strings I found in the wild, for two sites of clients of ours.

### CODE REVIEW

**Comment by jissereitsma** [comment]
Awesome! I'll add them right away, and will release a new version. Great work, thanks!

**Comment by ToonSpinISAAC** [comment]
Upgrading from 0.0.8 to the version with this commit in it, seems to have led to an 80% reduction in `log_visitor` row insertions.

**Comment by jissereitsma** [comment]
I assume this is a good thing right?

**Comment by ToonSpinISAAC** [comment]
Absolutely! It's the reason we've started using your plugin to begin with. We just hadn't expected the reduction to be this big. There is no issue here that I'm aware of, sorry if I spooked you. :sweat_smile:

**Comment by jissereitsma** [comment]
Awesome! :) I just wanted to make sure!

**Pull request merged**
